### ISSUE TITLE
Consider using a license that is more permissive

### ISSUE THREAD

**Issue by bj-rn** [michael-burk/VL.Radiosity#2]
Like for example [Boost ](https://www.boost.org/users/license.html), [MIT](https://opensource.org/license/mit/) or [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed).

I initially wanted to make a fork / pull request to fix some errors and make it a proper nuget. Then I decided against it, since I can't use it anyways because of the license you've chosen.

**Comment by michael-burk** [comment]
It's now MIT
